<?php
/*
 * @ https://EasyToYou.eu - IonCube v10 Decoder Online
 * @ PHP 7.2
 * @ Decoder version: 1.0.4
 * @ Release: 01/09/2021
 */

echo "<script>\r\n// Example starter JavaScript for disabling form submissions if there are invalid fields\r\n(function ()\r\n{\r\n\t'use strict';\r\n\twindow.addEventListener('load', function ()\r\n\t{\r\n\t\t// Fetch all the forms we want to apply custom Bootstrap validation styles to\r\n\t\tvar forms = document.getElementsByClassName('needs-validation');\r\n\t\t// Loop over them and prevent submission\r\n\t\tvar validation = Array.prototype.filter.call(forms, function (form)\r\n\t\t{\r\n\t\t\tform.addEventListener('submit', function (event)\r\n\t\t\t{\r\n\t\t\t\tif (form.checkValidity() === false)\r\n\t\t\t\t{\r\n\t\t\t\t\tevent.preventDefault();\r\n\t\t\t\t\tevent.stopPropagation();\r\n\t\t\t\t}\r\n\t\t\t\tform.classList.add('was-validated');\r\n\t\t\t}, false);\r\n\t\t});\r\n\t}, false);\r\n})();\r\n\r\n</script> \r\n\r\n\r\n<!--<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.1/jquery.js\"></script>-->\r\n\r\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.1/jquery-ui.js\"></script>\r\n\r\n<script>\r\n// Class definition\r\nvar controls = {\r\n\tleftArrow: '<i class=\"fal fa-angle-left\" style=\"font-size: 1.25rem\"></i>',\r\n\trightArrow: '<i class=\"fal fa-angle-right\" style=\"font-size: 1.25rem\"></i>'\r\n}\r\n\r\n\t\r\n\r\n    \$(function() {\r\n\t\t\r\n\t\t\r\n        \$( \"#visit_date\" ).datepicker({\r\n\t\t       \r\n\t\t\t     \r\n\t\t\t   \r\n\t\t\t   changeMonth: true,\r\n\t\t\t changeYear: true,\r\n\t\t\r\n        });\r\n\t\t\r\n\t\t\r\n        \$( \"#next_visit_date\" ).datepicker({\r\n\t\t       \r\n\t\t\t     \r\n\t\t\t   \r\n\t\t\t   changeMonth: true,\r\n\t\t\t changeYear: true,\r\n\t\t\r\n        });\r\n\t\t\r\n\t\t\r\n\t\t\r\n    });\r\n</script>\r\n\r\n <script>\r\n        \$(document).ready(function() {\r\n\t\t\t\r\n\t\t\t\$('.budget').keypress(function(event) {\r\n\t\t\t\tif (event.which != 46 && (event.which < 47 || event.which > 59))\r\n\t\t\t\t{\r\n\t\t\t\t\tevent.preventDefault();\r\n\t\t\t\t\tif ((event.which == 46) && (\$(this).indexOf('.') != -1)) {\r\n\t\t\t\t\t\tevent.preventDefault();\r\n\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t});\r\n\t\t\t\t\t\t\r\n\t\t\t\r\n\t });\r\n\r\n        </script>\r\n\t\t\r\n\r\n<script src=\"";
echo base_url();
echo "/public/js/menu/ajax.js\"></script>\r\n<script>\r\n\r\n\t// get the project value\r\n\t   // get the ndicator value\r\n    \$('body').delegate('#program', 'change', function () {\r\n\t\t\r\n\t\t\r\n\t\t\r\n        if (\$(this).val() != '') {\r\n\t\t\t\r\n\t\t\tvalue = \$(this).val();\r\n\t        //alert(val);\r\n\t\t\t\r\n\t\t\t\$.ajax({          \r\n        \ttype: \"GET\",\r\n        \turl: \"";
echo base_url() . "/reporting/organizational_data/monitoring_visit_report";
echo "/get_project\",\r\n        \tdata:'program_id='+value,\r\n        \tsuccess: function(data){\r\n        \t\t\$(\"#project_div\").html(data);\r\n\t\t\t\t//console.log(data);\r\n        \t}\r\n\t\t}); \r\n\t\t\t\r\n\t\t\t}\r\n    });\r\n\r\n///////\r\n\r\n    function addRow(tableID) {\r\n\r\n        var table = document.getElementById(tableID);\r\n        var rowCount = table.rows.length;\r\n        var row = table.insertRow(rowCount);\r\n        var colCount = table.rows[1].cells.length;\r\n\r\n        for (var i = 0; i < colCount; i++) {\r\n\r\n\r\n            var newcell = row.insertCell(i);\r\n            newcell.innerHTML = table.rows[1].cells[i].innerHTML;\r\n\r\n            //alert(newcell.childNodes);\r\n\r\n            // var k =newcell.childNodes.type;\r\n\r\n            //alert(k);\r\n\r\n            switch (newcell.childNodes[0].type) {\r\n\r\n                case \"text\":\r\n\r\n                    newcell.childNodes[0].value = \"\";\r\n\r\n                    break;\r\n\r\n                case \"checkbox\":\r\n\r\n                    newcell.childNodes[0].checked = false;\r\n\r\n                    break;\r\n\r\n                case \"select-one\":\r\n\r\n                    newcell.childNodes[0].selectedIndex = 0;\r\n\r\n                    break;\r\n\r\n                case \"textarea\":\r\n\r\n                    newcell.childNodes[0].value = \"\";\r\n\r\n                    break;\r\n\r\n            }\r\n\r\n        }\r\n\r\n\r\n\r\n       // \$(\".date_financing_approved\").datepicker(\"destroy\");\r\n\t\t\r\n\t\t\r\n\$('#dataTable_donor').on('focus', '.cls_agenda_date', function() {\r\n\t\$(this).datepicker({\r\n\t\t\tchangeMonth: true,\r\n\t\t\tchangeYear: true,\r\n\t\t\tformat: 'yyyy-mm-dd',\r\n\t\t\tDefault: 0,\r\n\t\t});\r\n});\t\t\r\n\t\t\r\n\t\t\r\n\r\n\r\n\r\n\r\n    }\r\n\t\r\n</script>";

?>