<?php
/*
 * @ https://EasyToYou.eu - IonCube v10 Decoder Online
 * @ PHP 7.2
 * @ Decoder version: 1.0.4
 * @ Release: 01/09/2021
 */

echo "﻿";
$db = Config\Database::connect();
echo "<style>\r\n    /*everything below this line is custom */\r\n       \r\n    #MapLocation{ height: 80px; width:766px}\r\n    #map{height:500px;}\r\n    #map.fullscreen{top:0 !important;left:0 !important;position: fixed !important;width: 100% !important;height: 100% !important;z-index: 1000;}\r\n</style><main id=\"js-page-content\" role=\"main\" class=\"page-content\">\r\n  <ol class=\"breadcrumb page-breadcrumb\">\r\n    <li class=\"breadcrumb-item\"><a href=\"";
echo base_url() . "/home";
echo "\">";
echo $main_title;
echo "</a></li>\r\n    <li class=\"breadcrumb-item active\">";
echo $title;
echo "</li>\r\n    <li class=\"position-absolute pos-top pos-right d-none d-sm-block\"><span class=\"js-get-date\"></span></li>\r\n  </ol>\r\n  <div id=\"panel-5\" class=\"panel\">\r\n<ul class=\"nav nav-tabs \" role=\"tablist\">\r\n    <li class=\"nav-item\"> <a class=\"nav-link\" href=\"";
echo site_url("dashboard");
echo "\" ><i class=\"fal fa-chart-bar mr-1\"></i> Overall Performance</a> </li>\r\n    <li class=\"nav-item\"> <a class=\"nav-link\" href=\"";
echo site_url("dashboard/project_overview");
echo "\" role=\"tab\"><i class=\"fal fa-chart-bar mr-1\"></i> Projects</a> </li>\r\n    <li class=\"nav-item\"> <a class=\"nav-link\" href=\"";
echo site_url("dashboard/county_performance");
echo "\" role=\"tab\"><i class=\"fal fa-chart-bar mr-1\"></i> County</a> </li>\r\n    \r\n    <li class=\"nav-item\"> <a class=\"nav-link\" href=\"";
echo site_url("dashboard/thematic_area_performance");
echo "\" role=\"tab\"><i class=\"fal fa-chart-bar mr-1\"></i> Thematic Area</a> </li>\r\n    <li class=\"nav-item\"> <a class=\"nav-link\" href=\"";
echo site_url("dashboard/ip_performance");
echo "\" role=\"tab\"><i class=\"fal fa-chart-bar mr-1\"></i> Implementing Partner</a> </li>\r\n    <li class=\"nav-item\"> <a class=\"nav-link active\" href=\"#\" role=\"tab\"><i class=\"fal fa-chart-bar mr-1\"></i>Cases Database</a></li>\r\n    \r\n    <li class=\"nav-item\"> <a class=\"nav-link\" href=\"";
echo site_url("dashboard/beneficiaries");
echo "\" role=\"tab\"><i class=\"fal fa-chart-bar mr-1\"></i>Beneficiaries</a></li>\r\n    <li class=\"nav-item\"> <a class=\"nav-link\" href=\"";
echo site_url("dashboard/budget_performance");
echo "\" role=\"tab\"><i class=\"fal fa-chart-bar mr-1\"></i>Budget Performance</a></li>\r\n</ul>\r\n    \r\n    \r\n    \r\n     \r\n<div class=\"tab-content border border-top-0 p-3\">\r\n  <div class=\"tab-pane fade show active\" id=\"tab_borders_icons-1\" role=\"tabpanel\">\r\n    <div class=\"row\"> \r\n      \r\n      <!-------Start Row ---->\r\n      <div class=\"col-lg-12\">\r\n        <div id=\"panel-1\" class=\"panel\" data-panel-fullscreen=\"false\">\r\n        \r\n          <div class=\"row\" style=\"padding-bottom:50px;\">\r\n          \r\n          \r\n             <div class=\"col-sm-2\">\r\n              <div class=\"col-sm-12 well\"> <br>\r\n                <h6><center>No. of Cases<br> New</center></h6>\r\n                <div id=\"number-box5\" class=\"dc-chart\"><span class=\"number-display\">\r\n                  ";
$query = $db->query("select count(*) as total FROM cases_database WHERE case_status=\"New\" ");
$row = $query->getRowArray();
echo $row["total"];
echo "                  </span>\r\n                     </div>\r\n              </div>\r\n            </div>\r\n\r\n\r\n            <div class=\"col-sm-2\">\r\n              <div class=\"col-sm-12 well\"> <br>\r\n                <h6>\r\n                  <center>No. of Cases <br> Ongoing</center>\r\n                </h6>\r\n                <div id=\"number-box2\" class=\"dc-chart\"><span class=\"number-display\">\r\n                  ";
$query = $db->query("select count(*) as total FROM cases_database WHERE case_status=\"Ongoing\" ");
$row = $query->getRowArray();
echo $row["total"];
echo "                  </span>\r\n                    </div>\r\n              </div>\r\n            </div>\r\n\r\n\r\n\r\n            <div class=\"col-sm-2\">\r\n              <div class=\"col-sm-12 well\"> <br>\r\n                <h6><center>No. of Cases <br> Stood Over Generally</center></h6>\r\n                <div id=\"number-box1\" class=\"dc-chart\"><span class=\"number-display\">\r\n                  ";
$query = $db->query("select count(*) as total FROM cases_database WHERE case_status=\"Stood Over Generally\" ");
$row = $query->getRowArray();
echo $row["total"];
echo "                  </span>\r\n                   </div>\r\n              </div>\r\n            </div>\r\n            \r\n            \r\n            \r\n            \r\n            \r\n            \r\n            \r\n            <div class=\"col-sm-2\">\r\n              <div class=\"col-sm-12 well\"> <br>\r\n                <h6><center>No. of Cases <br /> Out of Court Settled</center></h6>\r\n                <div id=\"number-box4\" class=\"dc-chart\"><span class=\"number-display\">\r\n                  ";
$query = $db->query("select count(*) as total FROM cases_database WHERE case_status=\"Out of Court Settlement\" ");
$row = $query->getRowArray();
echo $row["total"];
echo "                  </span>\r\n                     </div>\r\n              </div>\r\n            </div>\r\n            \r\n            \r\n            \r\n            \r\n            <div class=\"col-sm-2\" style=\"padding-left:0\">\r\n              <div class=\"col-sm-12 well\"> <br>\r\n                <h6><center>No. of Cases<br> Closed</center></h6>\r\n                <center>\r\n                  <div id=\"number-box3\" class=\"dc-chart\"><span class=\"number-display\">\r\n                    ";
$query = $db->query("select count(*) as total FROM cases_database WHERE case_status=\"Closed\"");
$row = $query->getRowArray();
echo $row["total"];
echo "                    </span>\r\n                    </div>\r\n                </center>\r\n              </div>\r\n            </div>\r\n            \r\n            \r\n            \r\n           \t<br>\r\n            \r\n          </div>\r\n          <!-------Row Ends here ----> \r\n          \r\n          \r\n<div class=\"row\"> \r\n          \r\n          <div class=\"col-lg-12\">\r\n            <div id=\"panel-1\" class=\"panel\" data-panel-fullscreen=\"false\">\r\n              <div class=\"panel-hdr\">\r\n                <h2> Summary Cases Type of GBV</h2>\r\n              </div>\r\n              \r\n               <div class=\"row\"> \r\n                <div class=\"col-lg-6\">\r\n                  <table class=\"highchart table table-hover table-bordered\" data-graph-container=\".. .. .highchart-caseOrigin\" data-graph-type=\"pie\">\r\n\t\t\t\t\t\t\t \r\n                              <thead>\r\n                                <tr>\r\n                                  <th bgcolor=\"#4189dd\">Type of GBV</th>\r\n                                  <th bgcolor=\"#4189dd\">No. of Cases</th>\r\n                                </tr>\r\n                              </thead>\r\n\r\n                              \r\n                              <tbody>\r\n                              \r\n                                <tr>                 \r\n                                   <td>Rape</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_gbv from cases_database left join cases_map_type_gbv on cases_map_type_gbv.workflow_id = cases_database.id where type_gbv IN (\"Rape\") ");
$row = $query->getRowArray();
echo $row["total_gbv"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n                                <tr>                 \r\n                                   <td>Defilement</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_gbv from cases_database left join cases_map_type_gbv on cases_map_type_gbv.workflow_id = cases_database.id where type_gbv IN (\"Defilement\") ");
$row = $query->getRowArray();
echo $row["total_gbv"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n\r\n                                <tr>                 \r\n                                   <td>Sexual Assault</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_gbv from cases_database left join cases_map_type_gbv on cases_map_type_gbv.workflow_id = cases_database.id where type_gbv IN (\"Sexual Assault\") ");
$row = $query->getRowArray();
echo $row["total_gbv"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n                                <tr>                 \r\n                                   <td>Physical Assault</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_gbv from cases_database left join cases_map_type_gbv on cases_map_type_gbv.workflow_id = cases_database.id where type_gbv IN (\"Physical Assault\") ");
$row = $query->getRowArray();
echo $row["total_gbv"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n                                <tr>                 \r\n                                   <td>Sodomy</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_gbv from cases_database left join cases_map_type_gbv on cases_map_type_gbv.workflow_id = cases_database.id where type_gbv IN (\"Sodomy\") ");
$row = $query->getRowArray();
echo $row["total_gbv"];
echo "                                    </td>\r\n                                </tr>\r\n                                \r\n                                <tr>                 \r\n                                   <td>Incest</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_gbv from cases_database left join cases_map_type_gbv on cases_map_type_gbv.workflow_id = cases_database.id where type_gbv IN (\"Incest\") ");
$row = $query->getRowArray();
echo $row["total_gbv"];
echo "                                    </td>\r\n                                </tr>\r\n                                \r\n                                \r\n                                <tr>                 \r\n                                   <td>Forced Marriage</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_gbv from cases_database left join cases_map_type_gbv on cases_map_type_gbv.workflow_id = cases_database.id where type_gbv IN (\"Forced Marriage\") ");
$row = $query->getRowArray();
echo $row["total_gbv"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n\r\n\r\n                                \r\n                                <tr>                 \r\n                                   <td>Denial of Resources</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_gbv from cases_database left join cases_map_type_gbv on cases_map_type_gbv.workflow_id = cases_database.id where type_gbv IN (\"Denial of Resources\") ");
$row = $query->getRowArray();
echo $row["total_gbv"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n\r\n                                <tr>                 \r\n                                   <td>Psych</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_gbv from cases_database left join cases_map_type_gbv on cases_map_type_gbv.workflow_id = cases_database.id where type_gbv IN (\"Psych\") ");
$row = $query->getRowArray();
echo $row["total_gbv"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n\r\n                                <tr>                 \r\n                                   <td>Emotional Abuse</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_gbv from cases_database left join cases_map_type_gbv on cases_map_type_gbv.workflow_id = cases_database.id where type_gbv IN (\"Emotional Abuse\") ");
$row = $query->getRowArray();
echo $row["total_gbv"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n\r\n                              </tbody>\r\n                            </table>\r\n                </div>\r\n                \r\n                \r\n                <div class=\"col-lg-6\">\r\n                  <h3 align=\"center\"> Summary Cases Type of GBV</h3>\r\n                  <div class=\"highchart-caseOrigin\"></div>\r\n                </div>\r\n              </div>\r\n              \r\n              \r\n            </div>\r\n          </div>\r\n          \r\n        </div>          \r\n          \r\n          \r\n          \r\n          \r\n        </div>\r\n      </div>\r\n      \r\n      \r\n      \r\n    </div>\r\n  </div>\r\n</div>    \r\n<!--KPI Achieved Targer-->    \r\n<div class=\"tab-content border border-top-0 p-3\">\r\n      <div class=\"tab-pane fade show active\" id=\"tab_borders_icons-1\" role=\"tabpanel\">\r\n      \r\n      \r\n          <!-------Start Row 2----> \r\n          \r\n        <div class=\"row\"> \r\n          \r\n          <div class=\"col-lg-12\">\r\n            <div id=\"panel-1\" class=\"panel\" data-panel-fullscreen=\"false\">\r\n              <div class=\"panel-hdr\">\r\n                <h2> Summary of New Cases Reported</h2>\r\n              </div>\r\n              \r\n               <div class=\"row\"> \r\n                <div class=\"col-lg-6\">\r\n                  <table class=\"highchart table table-hover table-bordered\" data-graph-container=\".. .. .highchart-container2\" data-graph-type=\"line\">\r\n\r\n                              <thead>\r\n                                <tr>\r\n                                  <th bgcolor=\"#4189dd\">Case Type</th>\r\n                                  <th bgcolor=\"#4189dd\">Total</th>\r\n                                </tr>\r\n                              </thead>\r\n\r\n                              \r\n                              <tbody>\r\n                              \r\n                                <tr>                 \r\n                                   <td>New</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select count(*) as total from cases_database WHERE case_type=\"New\"");
$row = $query->getRowArray();
echo $row["total"];
echo "\t\t\t\t\t\t\t\t   </td>\r\n                                </tr>\r\n\r\n                                <tr>                 \r\n                                   <td>Follow-up</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select count(*) as total from cases_database WHERE case_type=\"Follow Up\"");
$row = $query->getRowArray();
echo $row["total"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n\r\n                             \r\n                                \r\n\r\n                              </tbody>\r\n                            </table>\r\n                </div>\r\n                \r\n                \r\n                <div class=\"col-lg-6\">\r\n                  <div class=\"highchart-container2\"></div>\r\n                </div>\r\n              </div>\r\n              \r\n              \r\n            </div>\r\n          </div>\r\n          \r\n        </div>\r\n          <!-------Start Row 3 ----> \r\n\t\t  \r\n        <div class=\"row\"> \r\n          \r\n          <div class=\"col-lg-12\">\r\n            <div id=\"panel-1\" class=\"panel\" data-panel-fullscreen=\"false\">\r\n              <div class=\"panel-hdr\">\r\n                <h2> Summary of Survivor's Marital Status Weekly</h2>\r\n              </div>\r\n              \r\n               <div class=\"row\"> \r\n                <div class=\"col-lg-6\">\r\n                  <table class=\"highchart table table-hover table-bordered\" data-graph-container=\".. .. .highchart-container3\" data-graph-type=\"column\">\r\n\r\n                              <thead>\r\n                                <tr>\r\n                                  <th bgcolor=\"#4189dd\">Marital Status</th>\r\n                                  <th bgcolor=\"#4189dd\">Male</th>\r\n                                  <th bgcolor=\"#4189dd\">Female</th>\r\n                                </tr>\r\n                              </thead>\r\n\r\n                              \r\n                              <tbody>\r\n                              \r\n                                <tr>                 \r\n                                   <td>Single</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male) as total_male from cases_database WHERE marital_status=\"Single\" and gender =\"Male\" ");
$row = $query->getRowArray();
echo $row["total_male"];
echo "                                    </td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(female) as total_female from cases_database WHERE marital_status=\"Single\" and gender =\"Female\" ");
$row = $query->getRowArray();
echo $row["total_female"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n                                <tr>                 \r\n                                   <td>Married</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male) as total_male from cases_database WHERE marital_status=\"Married\" and gender =\"Male\" ");
$row = $query->getRowArray();
echo $row["total_male"];
echo "                                    </td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(female) as total_female from cases_database WHERE marital_status=\"Married\" and gender =\"Female\" ");
$row = $query->getRowArray();
echo $row["total_female"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n\r\n                                <tr>                 \r\n                                   <td>Cohabiting</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male) as total_male from cases_database WHERE marital_status=\"Cohabiting\" and gender =\"Male\" ");
$row = $query->getRowArray();
echo $row["total_male"];
echo "                                    </td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(female) as total_female from cases_database WHERE marital_status=\"Cohabiting\" and gender =\"Female\" ");
$row = $query->getRowArray();
echo $row["total_female"];
echo "                                    </td>\r\n                                </tr>\r\n                                \r\n                                <tr>                 \r\n                                   <td>Divorced</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male) as total_male from cases_database WHERE marital_status=\"Divorced\" and gender =\"Male\" ");
$row = $query->getRowArray();
echo $row["total_male"];
echo "                                    </td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(female) as total_female from cases_database WHERE marital_status=\"Divorced\" and gender =\"Female\" ");
$row = $query->getRowArray();
echo $row["total_female"];
echo "                                    </td>\r\n                                </tr>\r\n                                \r\n                                <tr>                 \r\n                                   <td>Separated</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male) as total_male from cases_database WHERE marital_status=\"Separated\" and gender =\"Male\" ");
$row = $query->getRowArray();
echo $row["total_male"];
echo "                                    </td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(female) as total_female from cases_database WHERE marital_status=\"Separated\" and gender =\"Female\" ");
$row = $query->getRowArray();
echo $row["total_female"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n\r\n                                <tr>                 \r\n                                   <td>Widowed</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male) as total_male from cases_database WHERE marital_status=\"Widowed\" and gender =\"Male\" ");
$row = $query->getRowArray();
echo $row["total_male"];
echo "                                    </td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(female) as total_female from cases_database WHERE marital_status=\"Widowed\" and gender =\"Female\" ");
$row = $query->getRowArray();
echo $row["total_female"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n                              </tbody>\r\n                            </table>\r\n                </div>\r\n                \r\n                \r\n                <div class=\"col-lg-6\">\r\n                  <div class=\"highchart-container3\"></div>\r\n                </div>\r\n              </div>\r\n              \r\n              \r\n            </div>\r\n          </div>\r\n          \r\n        </div>\r\n          <!-------Start Row 4----> \r\n\t\t   \r\n        <div class=\"row\"> \r\n          \r\n          <div class=\"col-lg-12\">\r\n            <div id=\"panel-1\" class=\"panel\" data-panel-fullscreen=\"false\">\r\n              <div class=\"panel-hdr\">\r\n                <h2> Summary of Case Context Weekly</h2>\r\n              </div>\r\n              \r\n               <div class=\"row\"> \r\n                <div class=\"col-lg-6\">\r\n                  <table class=\"highchart table table-hover table-bordered\" data-graph-container=\".. .. .highchart-container4\" data-graph-type=\"column\">\r\n\r\n                              <thead>\r\n                                <tr>\r\n                                  <th bgcolor=\"#4189dd\">Case Context</th>\r\n                                  <th bgcolor=\"#4189dd\">Male</th>\r\n                                  <th bgcolor=\"#4189dd\">Female</th>\r\n                                </tr>\r\n                              </thead>\r\n\r\n                              \r\n                              <tbody>\r\n                              \r\n                                <tr>                 \r\n                                   <td>Intimate Partner Violence</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male) as total_male from cases_database \r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\tleft join cases_map_case_context on cases_map_case_context.workflow_id = cases_database.id\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\twhere case_context IN (\"Intimate Partner Violence\") and cases_database.gender =\"Male\" ");
$row = $query->getRowArray();
echo $row["total_male"];
echo "                                    </td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(female) as total_female from cases_database \r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\tleft join cases_map_case_context on cases_map_case_context.workflow_id = cases_database.id\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\twhere case_context IN (\"Intimate Partner Violence\") and cases_database.gender =\"Female\" ");
$row = $query->getRowArray();
echo $row["total_female"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n                                <tr>                 \r\n                                   <td>Domestic Violence</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male) as total_male from cases_database \r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\tleft join cases_map_case_context on cases_map_case_context.workflow_id = cases_database.id\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\twhere case_context IN (\"Domestic Violence\") and cases_database.gender =\"Male\" ");
$row = $query->getRowArray();
echo $row["total_male"];
echo "                                    </td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(female) as total_female from cases_database \r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\tleft join cases_map_case_context on cases_map_case_context.workflow_id = cases_database.id\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\twhere case_context IN (\"Domestic Violence\") and cases_database.gender =\"Female\" ");
$row = $query->getRowArray();
echo $row["total_female"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n\r\n                                <tr>                 \r\n                                   <td>Child Abuse</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male) as total_male from cases_database \r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\tleft join cases_map_case_context on cases_map_case_context.workflow_id = cases_database.id\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\twhere case_context IN (\"Child Abuse\") and cases_database.gender =\"Male\" ");
$row = $query->getRowArray();
echo $row["total_male"];
echo "                                    </td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(female) as total_female from cases_database \r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\tleft join cases_map_case_context on cases_map_case_context.workflow_id = cases_database.id\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\twhere case_context IN (\"Child Abuse\") and cases_database.gender =\"Female\" ");
$row = $query->getRowArray();
echo $row["total_female"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n                                <tr>                 \r\n                                   <td>Early Mariage</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male) as total_male from cases_database \r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\tleft join cases_map_case_context on cases_map_case_context.workflow_id = cases_database.id\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\twhere case_context IN (\"Early Mariage\") and cases_database.gender =\"Male\" ");
$row = $query->getRowArray();
echo $row["total_male"];
echo "                                    </td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(female) as total_female from cases_database \r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\tleft join cases_map_case_context on cases_map_case_context.workflow_id = cases_database.id\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\twhere case_context IN (\"Early Mariage\") and cases_database.gender =\"Female\" ");
$row = $query->getRowArray();
echo $row["total_female"];
echo "                                    </td>\r\n                                </tr>\r\n                                \r\n                                \r\n                                <tr>                 \r\n                                   <td>Possible Sexual Exploitation</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male) as total_male from cases_database \r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\tleft join cases_map_case_context on cases_map_case_context.workflow_id = cases_database.id\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\twhere case_context IN (\"Possible Sexual Exploitation\") and cases_database.gender =\"Male\" ");
$row = $query->getRowArray();
echo $row["total_male"];
echo "                                    </td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(female) as total_female from cases_database \r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\tleft join cases_map_case_context on cases_map_case_context.workflow_id = cases_database.id\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\twhere case_context IN (\"Possible Sexual Exploitation\") and cases_database.gender =\"Female\" ");
$row = $query->getRowArray();
echo $row["total_female"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n\r\n\r\n                                <tr>                 \r\n                                   <td>Harmful Traditional Practices</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male) as total_male from cases_database \r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\tleft join cases_map_case_context on cases_map_case_context.workflow_id = cases_database.id\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\twhere case_context IN (\"Harmful Traditional Practices\") and cases_database.gender =\"Male\" ");
$row = $query->getRowArray();
echo $row["total_male"];
echo "                                    </td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(female) as total_female from cases_database \r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\tleft join cases_map_case_context on cases_map_case_context.workflow_id = cases_database.id\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\twhere case_context IN (\"Harmful Traditional Practices\") and cases_database.gender =\"Female\" ");
$row = $query->getRowArray();
echo $row["total_female"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n\r\n                              </tbody>\r\n                            </table>\r\n                </div>\r\n                \r\n                \r\n                <div class=\"col-lg-6\">\r\n                  <div class=\"highchart-container4\"></div>\r\n                </div>\r\n              </div>\r\n              \r\n              \r\n            </div>\r\n          </div>\r\n          \r\n        </div>\r\n        \r\n        \r\n\r\n        \r\n          <!-------Start Row 4----> \r\n\t\t   \r\n        <div class=\"row\"> \r\n          \r\n          <div class=\"col-lg-12\">\r\n            <div id=\"panel-1\" class=\"panel\" data-panel-fullscreen=\"false\">\r\n              <div class=\"panel-hdr\">\r\n                <h2> Summary of Case Origin</h2>\r\n              </div>\r\n              \r\n               <div class=\"row\"> \r\n                <div class=\"col-lg-6\">\r\n                  <table class=\"highchart table table-hover table-bordered\" data-graph-container=\".. .. .highchart-caseOrigin\" data-graph-type=\"column\">\r\n\r\n                              <thead>\r\n                                <tr>\r\n                                  <th bgcolor=\"#4189dd\">County</th>\r\n                                  <th bgcolor=\"#4189dd\">Male</th>\r\n                                  <th bgcolor=\"#4189dd\">Female</th>\r\n                                </tr>\r\n                              </thead>\r\n\r\n                              \r\n                              <tbody>\r\n                              \r\n                                <tr>   \r\n                  ";
$query = $db->query("select name, sum(male) as tot_male, sum(female) as tot_female from cases_database left join mas_county on mas_county.id = cases_database.county group by county");
$results = $query->getResultArray();
foreach ($results as $row) {
    echo "                  <tr>\r\n                    <td>";
    echo $row["name"];
    echo "</td>\r\n                   <td>";
    echo $row["tot_male"];
    echo "</td>\r\n                   <td>";
    echo $row["tot_female"];
    echo "</td>\r\n                  </tr>\r\n                  ";
}
echo "                                   \r\n                                   \r\n                                </tr>\r\n\r\n                            \r\n\r\n\r\n                              \r\n                                \r\n                                \r\n\r\n                              </tbody>\r\n                            </table>\r\n                </div>\r\n                \r\n                \r\n                <div class=\"col-lg-6\">\r\n                  <div class=\"highchart-caseOrigin\"></div>\r\n                </div>\r\n              </div>\r\n              \r\n              \r\n            </div>\r\n          </div>\r\n          \r\n        </div>\r\n        \r\n        \r\n          <!-------Start Row 6----> \r\n\t\t   \r\n        \r\n<div class=\"row\"> \r\n          \r\n          <div class=\"col-lg-12\">\r\n            <div id=\"panel-1\" class=\"panel\" data-panel-fullscreen=\"false\">\r\n              \r\n              <div class=\"panel-hdr\">\r\n                <h2> Summary of Services Provide</h2>\r\n              </div>\r\n              \r\n               <div class=\"row\"> \r\n                <div class=\"col-lg-6\">\r\n                  <table class=\"highchart table table-hover table-bordered\" data-graph-container=\".. .. .highchart-sp\" data-graph-type=\"pie\">\r\n\t\t\t\t\t\t\t \r\n                              <thead>\r\n                                <tr>\r\n                                  <th bgcolor=\"#4189dd\">Services Provide</th>\r\n                                  <th bgcolor=\"#4189dd\">No. of Cases</th>\r\n                                </tr>\r\n                              </thead>\r\n\r\n                              \r\n                              <tbody>\r\n                              \r\n                                <tr>                 \r\n                                   <td>Ref Safe House</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_sp from cases_database left join cases_map_services_provided on cases_map_services_provided.workflow_id = cases_database.id where services_provided IN (\"Ref Safe House\") ");
$row = $query->getRowArray();
echo $row["total_sp"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n                                <tr>                 \r\n                                   <td>Shelter Services Ref</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_sp from cases_database left join cases_map_services_provided on cases_map_services_provided.workflow_id = cases_database.id where services_provided IN (\"Shelter Services Ref\") ");
$row = $query->getRowArray();
echo $row["total_sp"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n\r\n                                <tr>                 \r\n                                   <td>Health Services</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_sp from cases_database left join cases_map_services_provided on cases_map_services_provided.workflow_id = cases_database.id where services_provided IN (\"Health Services\") ");
$row = $query->getRowArray();
echo $row["total_sp"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n                                <tr>                 \r\n                                   <td>Medical Services</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_sp from cases_database left join cases_map_services_provided on cases_map_services_provided.workflow_id = cases_database.id where services_provided IN (\"Medical Services\") ");
$row = $query->getRowArray();
echo $row["total_sp"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n                                <tr>                 \r\n                                   <td>Psychosocial Services</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_sp from cases_database left join cases_map_services_provided on cases_map_services_provided.workflow_id = cases_database.id where services_provided IN (\"Psychosocial Services\") ");
$row = $query->getRowArray();
echo $row["total_sp"];
echo "                                    </td>\r\n                                </tr>\r\n                                \r\n                                <tr>                 \r\n                                   <td>Counselling Services</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_sp from cases_database left join cases_map_services_provided on cases_map_services_provided.workflow_id = cases_database.id where services_provided IN (\"Counselling Services\") ");
$row = $query->getRowArray();
echo $row["total_sp"];
echo "                                    </td>\r\n                                </tr>\r\n                                \r\n                                \r\n                                <tr>                 \r\n                                   <td>Mediation Services</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_sp from cases_database left join cases_map_services_provided on cases_map_services_provided.workflow_id = cases_database.id where services_provided IN (\"Mediation Services\") ");
$row = $query->getRowArray();
echo $row["total_sp"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n\r\n\r\n                                \r\n                                <tr>                 \r\n                                   <td>Court Process</td>\r\n                                   <td>\r\n\t\t\t\t\t\t\t\t\t";
$query = $db->query("select sum(male+female) as total_sp from cases_database left join cases_map_services_provided on cases_map_services_provided.workflow_id = cases_database.id where services_provided IN (\"Court Process\") ");
$row = $query->getRowArray();
echo $row["total_sp"];
echo "                                    </td>\r\n                                </tr>\r\n\r\n                              </tbody>\r\n                            </table>\r\n                </div>\r\n                \r\n                \r\n                <div class=\"col-lg-6\">\r\n                   <h3 align=\"center\"> Summary of Services Provide</h3>\r\n                  <div class=\"highchart-sp\"></div>\r\n                </div>\r\n              </div>\r\n              \r\n              \r\n            </div>\r\n          </div>\r\n          \r\n        </div>        \r\n        \r\n          <!-------Start Row ----> \r\n\r\n\r\n\r\n      </div>\r\n    </div>    \r\n    \r\n<!--KPI ON Track-->   \r\n\r\n    \r\n    \r\n\r\n\r\n<!--KPI Under Performing-->\r\n\r\n    \r\n    \r\n\r\n\r\n<!--END-->\r\n  </div>\r\n</main>\r\n";

?>