<?php
/*
 * @ https://EasyToYou.eu - IonCube v10 Decoder Online
 * @ PHP 7.2
 * @ Decoder version: 1.0.4
 * @ Release: 01/09/2021
 */

echo "\r\n<script>\r\n// Example starter JavaScript for disabling form submissions if there are invalid fields\r\n(function ()\r\n{\r\n\t'use strict';\r\n\twindow.addEventListener('load', function ()\r\n\t{\r\n\t\t// Fetch all the forms we want to apply custom Bootstrap validation styles to\r\n\t\tvar forms = document.getElementsByClassName('needs-validation');\r\n\t\t// Loop over them and prevent submission\r\n\t\tvar validation = Array.prototype.filter.call(forms, function (form)\r\n\t\t{\r\n\t\t\tform.addEventListener('submit', function (event)\r\n\t\t\t{\r\n\t\t\t\tif (form.checkValidity() === false)\r\n\t\t\t\t{\r\n\t\t\t\t\tevent.preventDefault();\r\n\t\t\t\t\tevent.stopPropagation();\r\n\t\t\t\t}\r\n\t\t\t\tform.classList.add('was-validated');\r\n\t\t\t}, false);\r\n\t\t});\r\n\t}, false);\r\n})();\r\n\r\n</script> \r\n\r\n<script>\r\n\r\n    \$('body').delegate('#activity_type', 'change', function () {\r\n\t\t\r\n       if (\$(this).val() != '') {\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t //alert(\$(this).val());\r\n\t\t\t if (\$(this).val() == 'Non-Budget Activity') {\r\n\t\t\t\t \r\n\t\t\t\t//alert(\$(this).val());\r\n\t\t\t\t\r\n\t\t\t\t\$(\".DivNonbudgetActivity\").fadeIn();\r\n\t\t\t\t\$(\".DivbudgetActivity\").fadeOut();\r\n\t\t\t\t  \r\n\t\t\t\t \r\n\t\t\t }\r\n\t\t\t \r\n\t\t\t \r\n\t\t\t if (\$(this).val() == 'Budget Activity') {\r\n\t\t\t\t \r\n\t\t\t\t//alert(\$(this).val());\r\n\t\t\t\t\$(\".DivbudgetActivity\").fadeIn();\r\n\t\t\t\t\$(\".DivNonbudgetActivity\").fadeOut();\r\n\t\t\t\t  \r\n\t\t\t\t \r\n\t\t\t }\r\n\t\t\t \r\n\t\t\t\r\n\t\t\t\r\n\t\t\t}\r\n   });\r\n   \r\n\r\n  /**********************************************************************************************************************/\r\n\t   // get the ndicator value\r\n    function get_activity(project_id, activity_id) {\r\n\t\t\r\n\t\t//alert(project_id);\r\n\t\t//alert(activity_id);\r\n\t\t\r\n        if (activity_type != '') {\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t//alert(val);\r\n\t\t\t\r\n\t\t\t// ajax 1\r\n\t\t\t\$.ajax({          \r\n        \ttype: \"GET\",\r\n        \turl: \"";
echo base_url() . "/planning/project_me_plan";
echo "/get_budget_activity\",\r\n        \tdata:'activity_id='+activity_id + '&project_id='+project_id ,\r\n        \tsuccess: function(data){\r\n        \t\t//\$(\"#year\").html(data);\r\n\t\t\t\t//console.log(data);\r\n\t\t\t\t\$(\"#activity_code\").val(data);\r\n\t\t\t\t\r\n        \t\t}\r\n\t\t\t\r\n\t\t\t}); \r\n\t\t\t\r\n\t\t\t\r\n\t\t\t// ajax 2\r\n\t\t\t\$.ajax({          \r\n        \ttype: \"GET\",\r\n        \turl: \"";
echo base_url() . "/planning/project_me_plan";
echo "/get_budget_activity2\",\r\n        \tdata:'activity_id='+activity_id + '&project_id='+project_id ,\r\n        \tsuccess: function(data){\r\n        \t\t\$(\"#DivPlanning\").html(data);\r\n\t\t\t\t//console.log(data);\r\n\t\t\t\t\r\n        \t\t}\r\n\t\t\t\r\n\t\t\t }); \r\n\t\t\t\r\n\t\t\t////\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t}\r\n\t}\r\n\t      \r\n /***********************************************************************************************************************/  \r\n</script>\r\n\r\n\r\n";

?>